import type { OrderDetail } from '../types/orderDetail'

export const ORDER_ID = '01JQZ00000000000000ORD01'
export const LINE_ID = '01JQZ0000000000000LINE01'
export const PACKAGE_ID = '01JQZ0000000000000PACK01'
export const CHILD_PACKAGE_ID = '01JQZ0000000000000PACK02'

/**
 * Commande complète, à la forme exacte d'`OrderDetailResource`.
 *
 * Aucun champ inventé : les services portent leurs trois sous-objets
 * `operational` / `billing` / `providerCost`, et il n'y a pas d'`OrderStop`.
 */
export function makeOrderDetail(overrides: Partial<OrderDetail> = {}): OrderDetail {
  return {
    id: ORDER_ID,
    organizationId: '01JQZ0000000000000000ORG1',
    orderNumber: 'CMD-2026-000001',
    externalReference: 'EXT-42',
    customerReference: null,
    orderType: null,
    groupCode: null,
    parentOrderId: null,
    orderDate: '2026-08-01',
    source: 'internal',
    status: 'draft',
    statusLabel: 'Brouillon',
    allowsContentChanges: true,
    allowedTransitions: ['confirmed', 'cancelled'],
    internalRemark: null,
    workerRemark: null,
    weight: null,
    volume: null,
    packageCount: 2,
    currencyCode: 'MAD',
    customerId: '01JQZ000000000000000CUST',
    agencyId: '01JQZ0000000000000000AGY1',
    depotId: null,
    customer: { id: '01JQZ000000000000000CUST', code: 'CLI001', name: 'Client Alpha' },
    agency: { id: '01JQZ0000000000000000AGY1', code: 'AG01', name: 'Agence Nord' },
    lines: [
      {
        id: LINE_ID,
        orderId: ORDER_ID,
        catalogItemId: '01JQZ00000000000000ITEM1',
        parentLineId: null,
        externalReference: null,
        articleCode: 'ART-9',
        barcode: null,
        name: 'Carton renforcé',
        description: null,
        quantity: 10,
        reservedQuantity: null,
        preparedQuantity: null,
        deliveredQuantity: null,
        weight: null,
        volume: null,
        length: null,
        width: null,
        height: null,
        purchasePrice: null,
        sellingPrice: null,
        status: null,
        fromCatalog: true,
      },
    ],
    packages: [
      {
        id: PACKAGE_ID,
        orderId: ORDER_ID,
        parentPackageId: null,
        packageTypeId: null,
        groupingTypeId: null,
        currentStockLocationId: null,
        barcode: null,
        reference: 'PAL-1',
        description: null,
        quantity: 1,
        weight: 12.5,
        volume: 0.6,
        length: 120,
        width: 80,
        height: 145,
        status: 'pending',
        packageType: { id: '01JQZ0000000000000TYPE01', code: 'PAL', name: 'Palette' },
        lines: [{ id: '01JQZ0000000000000PKLN01', orderLineId: LINE_ID, quantity: 4 }],
      },
      {
        id: CHILD_PACKAGE_ID,
        orderId: ORDER_ID,
        parentPackageId: PACKAGE_ID,
        packageTypeId: null,
        groupingTypeId: null,
        currentStockLocationId: null,
        barcode: null,
        reference: 'CTN-1',
        description: null,
        quantity: 1,
        weight: null,
        volume: null,
        length: null,
        width: null,
        height: null,
        status: 'pending',
        lines: [],
      },
    ],
    services: [
      {
        id: '01JQZ0000000000000SRVC01',
        orderId: ORDER_ID,
        serviceId: '01JQZ00000000000000SERV1',
        addressId: '01JQZ00000000000000ADDR1',
        serviceNumber: 'SRV-1',
        sequence: 1,
        operational: {
          requestedDate: '2026-08-05',
          requestedFrom: null,
          requestedTo: null,
          quantity: 1,
          unit: 'colis',
          requiredTimeMinutes: 30,
          remainingTimeMinutes: 30,
          weight: null,
          volume: null,
          packageCount: 2,
          instructions: 'Sonner au portail.',
        },
        billing: { customerUnitPrice: 120, customerTotalPrice: 120 },
        providerCost: { providerUnitCost: 80, providerTotalCost: 80 },
        status: 'draft',
        service: {
          id: '01JQZ00000000000000SERV1',
          organizationId: '01JQZ0000000000000000ORG1',
          code: 'LIV',
          name: 'Livraison standard',
          unit: 'colis',
          defaultDurationMinutes: 30,
          billableToCustomer: true,
          payableToProvider: true,
          requiresAddress: true,
          requiresContact: true,
          status: 'active',
        },
        contacts: [
          {
            id: '01JQZ0000000000000CTCT01',
            orderServiceId: '01JQZ0000000000000SRVC01',
            contactId: null,
            contactRole: 'delivery',
            firstName: 'Sophie',
            lastName: 'Bernard',
            phone: null,
            mobile: '+212600000000',
            email: null,
            isPrimary: true,
            createdAt: '2026-08-01T09:00:00.000000Z',
          },
        ],
        packages: [
          {
            id: '01JQZ0000000000000SVPK01',
            packageId: PACKAGE_ID,
            quantity: 1,
            handlingInstructions: null,
            status: 'pending',
          },
        ],
      },
    ],
    createdAt: '2026-08-01T09:00:00.000000Z',
    updatedAt: '2026-08-01T09:00:00.000000Z',
    ...overrides,
  }
}

/** Réponse de `GET /orders/{order}/packages/tree`, hiérarchie déjà assemblée. */
export const PACKAGE_TREE = [
  {
    id: PACKAGE_ID,
    parentPackageId: null,
    barcode: null,
    reference: 'PAL-1',
    quantity: 1,
    weight: null,
    volume: null,
    status: 'pending',
    children: [
      {
        id: CHILD_PACKAGE_ID,
        parentPackageId: PACKAGE_ID,
        barcode: null,
        reference: 'CTN-1',
        quantity: 1,
        weight: null,
        volume: null,
        status: 'pending',
        children: [],
      },
    ],
  },
]
